### ISSUE TITLE
is this is working for Rpi 4

### ISSUE THREAD

**Issue by MyraBaba** [liri-archive/eglfs#13]
is this is working for Rpi 4 ?

**Comment by plfiorini** [comment]
Was working on Rpi 3 with mesa, should work the same for Rpi 4, but I can't check myself due to the lack of a viable image for that system.

**Comment by MyraBaba** [comment]
gpu is changed in rpi4

**Comment by plfiorini** [comment]
If mesa supports rpi4 it should work, that's the point of the open source drivers.

**Comment by plfiorini** [comment]
With work I mean showing an image on the screen.
It's entirely possible it will be slow. The open source driver had very poor performance on rpi2 and I never bothered testing with rpi3.

**Comment by MyraBaba** [comment]
in rpi3 we were happy all the performance specifically for eglfs. 

now all game changed and not much information . 

keep digging for the golden knowledge or our own grave.... :)

**Comment by plfiorini** [comment]
I dream of using all those boards that I have collected over the years :)
Raspberry Pi boards are like soccer players figurines. You bought the first one and you keep buying it over and over again, although at times it's such a disappointing experience.

**Comment by MyraBaba** [comment]
we are very happy with rpi3b+ but cant find , there is not enough production these days or stopped for rpi4
