### ISSUE TITLE
can't solve the liri1logind dependency

### ISSUE THREAD

**Issue by breeze256** [liri-archive/eglfs#23]
Installing liri-eglfs-git aur package requires the liri1logind dependency, but liri1logind has just been removed from libliri. This issue makes me cannot to install eglfs. How can I solve this problem?
[CMakeOutput.log](https://github.com/lirios/eglfs/files/10145906/CMakeOutput.log)

**Comment by plfiorini** [comment]
This repository is now obsolete, packages will be updated ASAP.
