### ISSUE TITLE
Link incomplete?

### ISSUE THREAD

**Issue by schnitzeltony** [liri-archive/eglfs#8]
When trying to start liri-session it complains with:

> liri-shell: symbol lookup error: /usr/lib/plugins/liri/egldeviceintegrations/libeglfs-kms-integration.so: undefined symbol: glEGLImageTargetTexture2DOES

With my limited cmake skills I tried [1] but situation remains.

[1] https://github.com/schnitzeltony/eglfs/commit/4b2f378339f525584147dea17ac31789947f9a20

**Comment by plfiorini** [comment]
I get a different error on Arch Linux: it doesn't find the eglQueryString symbol from libLiri1EglFSDeviceIntegration.so.1

Doesn't happen on Fedora 29.

I hate CMake.

**Comment by schnitzeltony** [comment]
I considered that fixed by
https://github.com/lirios/eglfs/commit/2da23af62476ce88b417b86efcdf1a215db597f2

**Comment by plfiorini** [comment]
No that fixed the issue with `libeglfs-kms-integration.so`, but https://github.com/lirios/eglfs/commit/144edef457fd833962491dff938f1d5ead7e6efc fixes the same issue with `libLiri1EglFSDeviceIntegration.so.1`. Just tested on Arch where I previously had the problem and it's fixed.

**Comment by plfiorini** [comment]
@schnitzeltony Which mesa version? I assume you are still using open source libraries.

**Comment by schnitzeltony** [comment]
Yes - no graphic blobs. Mesa version is 18.1.9

**Comment by schnitzeltony** [comment]
Fixed by https://github.com/lirios/eglfs/commit/3c8413972e4fb7fb930035780daf24e35111c866
